import CardKnjiga from '@/components/CardKnjiga';
import { useStateContext } from '@/context/StateContext'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { Container, Row, Button } from 'react-bootstrap';
import Navbar from '../components/Navbar';


export default function Home({ knjige1 }) {
  const { knjige, knjigePrikaz , setknjigePrikaz, setknjige} = useStateContext();
  
  useEffect(() => {
    setknjige(knjige1)
  }, [])

  useEffect(() => {
    setknjigePrikaz(knjige)
  }, [knjige])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Navbar />
      <Container style={{height:'100vh'}}>
        <h1>Pdf zapisi:</h1>
        <Row>
          {knjigePrikaz && knjigePrikaz.map((knjiga, index) => (
            <div key={index} className="col-lg-4 mb-3">
              <CardKnjiga naslov={knjiga.naslov} autor={knjiga.autor} id={knjiga.id}  />
            </div>
          ))}
        </Row>
      </Container>
    </>
  )
}

export async function getStaticProps() {
 
  const response = await fetch('http://localhost:3000/api/knjige'); 
  const data = await response.json();

  return {
    props: {
      knjige1: data 
    }
  };
}
